apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::423104517001:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-A4ND7VSTAS0C
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::423104517001:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-17T03:10:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1132"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9853ba98-faa0-4c1f-b2a3-8877469edea1
